CREATE TABLE
  IF NOT EXISTS tasks (
    "object_name" text,
    "task_name" text,
    "task_type" int,
    "uuid" text,
    "date" text,
    "author" text,
    "author_id" text NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    "creator_id" text,
    "end_user" text,
    "end_user_id" text NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    "deadline_date" text,
    "task_info" text,
    "agree_status" boolean,
    "linked_task_id" text,
    "approval_list" text ARRAY,
    "comment" text,
    "enable_dead_date_shift" boolean,
    "layout_type" int,
    "period_start" text,
    "period_end" text,
    "holiday_mayker" text,
    "substitutional" text,
    "kontragent" text,
    "organization" text,
    "sum" text,
    "payment_date" text,
    "payment_purpose" text,
    CONSTRAINT tasks_pkey PRIMARY KEY ("uuid")
  );
