version: '3.7'

services:
  dynamo:
    container_name: local-dynamodb
    image: amazon/dynamodb-local
    networks:
      - local
    ports:
      - "12364:8000"
    restart: always
    volumes:
      - dynamodata:/home/dynamodblocal
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: project
    working_dir: /home/dynamodblocal
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ."

  backend:
    build:
      context: ../../
    container_name: backend-local
    networks:
      - local
    depends_on:
      - dynamo
    ports:
      - '1140:1140'
    restart: always

networks:
  local:
    name: local

volumes:
  dynamodata: {}
