version: '3.7'

services:
  db:
    image: postgres:latest
    container_name: db
    ports:
      - '5433:5432'
    restart: always
    volumes:
      - ./tmp/db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: project

  backend:
    build:
      context: ../../
    container_name: backend-local
    depends_on:
      - db
    ports:
      - '1140:1140'
    restart: always
